name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Pods
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push
